# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool: pc-local

steps:
- task: Gradle@2
  displayName: 'Build project'
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'Path'
    jdkUserInputPath: 'C:\\Program Files\\Java\\jdk-11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'

- task: Gradle@2
  displayName: 'Run tests and aggregate results'
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'Path'
    jdkUserInputPath: 'C:\\Program Files\\Java\\jdk-11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'clean test aggregate'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'target/site/serenity'
    artifactName: 'SerenityReports'
    publishLocation: 'Container'